name: hangukverse
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# App version
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^3.0.3

  # Supabase
  supabase_flutter: ^2.10.3
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lint rules
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/Login/

  fonts:
    - family: Kalnia
      fonts:
        - asset: assets/fonts/Kalnia/Kalnia-VariableFont_wdth,wght.ttf
